

# Specify your environment by making a copy of this file to create a file in your root directory called config.yml with your environment settings.

# host e.g. localhost:3000 or discourse.my_domain.com
host: https://forum.example.com

# api user (can effect results returned, e.g. .categories method returns only the categories your api_username can see)
# create a new client with when changing api user
api_username: coolguy

# api key from Discourse admin panel /admin/api/keys
api_key: bc0f22c284dfc5a18c0a6ea003e953eebae893
